### PR TITLE
Allow read access to fmt.Stringer Keys and reference values on maps

### PR DESCRIPTION
**Pull request by HRogge**

### CODE REVIEW

**Comment by dhubler** [comment]
any chance you can add some test cases?

**Comment by HRogge** [comment]
I will try to add a few tests tomorrow... the changes itself look okay for you?

**Comment by dhubler** [comment]
yes.

**Comment by HRogge** [comment]
fun fact about the tests for keys of maps. The sort API of go doesn't call the comparator for slices with length 0 or 1, so it never fails with a "bad type" unless the map contains at least two elements.

**Comment by dhubler** [comment]
feature ;)

all the pieces look there. i'll run test and merge this in this evening.

**Comment by HRogge** [comment]
I have code for doing the write access for custom typed fields (without writing custom handlers)... do you want to merge this and take the new one in a new pull request?

**Comment by dhubler** [comment]
yes, merging in would be better.

**Comment by HRogge** [comment]
I have pushed a branch called custommarshallerpreview to my own repository so you can have a look what comes next. I will rebase it to "master" and send a pull request for it as soon as this pull is merged.

**Comment by dhubler** [comment]
I was thinking you'd squash the 2 commits on your end and submit a single,
cohesive PR that supports r/w for structs and stringers

**Comment by HRogge** [comment]
if you prefer the change (r/w) as a single commit, I can squash them all and open a new PR.

**Pull request closed without merging**
