### PR TITLE
Adding xml support

### PR DESCRIPTION
**Pull request by sebastien-guay**
Adding xml support

### CODE REVIEW

**Comment by dhubler** [comment]
got it, thanks for the MR.  It will take me a few days to go thru.  BTW: I am rebasing it on master now as this forked from master 6 months ago and I have a couple conflicts to go thru.

**Comment by sebastien-guay** [comment]
> got it, thanks for the MR. It will take me a few days to go thru. BTW: I am rebasing it on master now as this forked from master 6 months ago and I have a couple conflicts to go thru.

Ok Thanks, I merged the freeconf/yang master branch in my branch on September 5th and resolved all the conflicts.

**Comment by dhubler** [comment]
fully rebased branch here:
 https://github.com/freeconf/yang/tree/xml
looking thru logic now...

**Comment by dhubler** [comment]
organizing my comments on rebased branch, still working thru this tho
 https://github.com/freeconf/yang/pull/95

**Comment by dhubler** [comment]
accepted but closing as this was incorporated from different PR

**Pull request closed without merging**
